version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/almabaseca
    ports:
      - 8000:8000
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"